spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/runoob
  application:
    name: mongoweb
server:
  port: 8889
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG